
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virt-joiner-role
rules:
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["instancetype.kubevirt.io"]
    resources: ["virtualmachineclusterinstancetypes", "virtualmachineinstancetypes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

