---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virt-joiner-binding
subjects:
  - kind: ServiceAccount
    name: virt-joiner
    namespace: openshift-cnv
roleRef:
  kind: ClusterRole
  name: virt-joiner-role
  apiGroup: rbac.authorization.k8s.io