---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-joiner
  namespace: openshift-cnv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: virt-joiner
  template:
    metadata:
      labels:
        app: virt-joiner
    spec:
      serviceAccountName: virt-joiner
      containers:
        - name: virt-joiner
          image: ghcr.io/thewizardofozolins/virt-joiner:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
          envFrom:
            - secretRef:
                name: virt-joiner-config
          volumeMounts:
            - name: certs
              mountPath: /var/run/secrets/serving-cert
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: virt-joiner-certs
