apiVersion: v1
kind: Service
metadata:
  name: virt-joiner
  namespace: openshift-cnv
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: virt-joiner-certs
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: virt-joiner
