apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: virt-joiner-webhook
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: virt-joiner.virtualisation.svc
    clientConfig:
      service:
        name: virt-joiner
        namespace: openshift-cnv
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: ["kubevirt.io"]
        apiVersions: ["v1"]
        resources: ["virtualmachines"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    failurePolicy: Fail
