apiVersion: v1
kind: Secret
metadata:
  name: virt-joiner-config
  namespace: openshift-cnv
type: Opaque
stringData:
  IPA_HOST: "idm-46c2.syd.sigaint.au"
  IPA_USER: "admin"
  IPA_PASS: "Dispatch2-Lunacy3-Detergent2-Exemption1-Galvanize3"
  DOMAIN: "sigaint.au"
